version: '3'
services:
  selenium:
    image: selenium/standalone-chrome
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
  web:
    image: icons8
    build: .
    volumes:
      - .:/app
    command: /bin/bash -c "sleep 5 && python main.py"
    depends_on:
      - selenium
    environment:
      - TOKEN
      - ALLOWED_USER_IDS
